name: test1

on:
  workflow_dispatch:
    inputs: 
      enviroment:
        type: chioce
        options:
        - DEV
        - UAT
      schemas:
        type: array
        description: "Target schemas"

jobs:
  task:
    runs-on: [self_hosted]
    steps:
      - name: Check
      - uses: actions/checkout@v1
        run: |
          echo ${{github.events.inputs.schemas}}
        
      
