name: test1

on:
  workflow_dispatch:
    inputs: 
      enviroment:
        type: choice
        options:
        - DEV
        - UAT
      schemas:
        type: string
      branch_name:
        type: string
jobs:
  task:
    runs-on: ubuntu-latest
    env: 
      BRANCH_NAME : ${{ github.event.inputs.schemas }} 
    steps:
    - uses: actions/checkout@v1
      with:  "{$BRANCH_NAME}"
    - name: Check
      run: |
          echo -e '${{ github.event.inputs.schemas }}'
        
      
