name: test1

on:
  workflow_dispatch:
    inputs: 
      enviroment:
        type: choice
        options:
        - DEV
        - UAT
      schemas:
        type: string
      branch_name:
        type: string
      list_of_values:
        description: 'Enter a list of values (comma-separated)'
        required: true
jobs:
  list_of_values_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the list of values input
        run: |
          list_of_values="${{ inputs.list_of_values }}"
          IFS=';' read -ra values <<< "$list_of_values"
          
          # Now you have individual values in the 'values' array
          for value in "${values[@]}"; do
            echo "Value: $value"
          done

  switch_branch_job:
    runs-on: ubuntu-latest
    env: 
      BRANCH_NAME : ${{ github.event.inputs.branch_name }} 
    steps:
    - uses: actions/checkout@v1
      with:  
        ref: ${{ github.event.inputs.branch_name }}
    - name: Get_branch
      run: |
          #echo -e 'Running on default: ${{ steps.branch-name.outputs.current_branch }}   
          #echo -e 'var name: ${{ github.event.inputs.branch_name }}'
          
          current_branch="origin/"$BRANCH_NAME
          base_branch="origin/main"
          echo "branch name: $current_branch"
          echo "branch name: $base_branch"
          
          changed_files=$(git diff --name-only $base_branch $current_branch)
          #echo "::set-output name=changed_files::$changed_files"   
          
          for file in ${changed_files[@]; do
            echo "Files: $file"
          done
          
 
